### ISSUE TITLE
getBoundingClientRect of null error

### ISSUE THREAD

**Issue by Widus** [martinnov92/React-Splitters#9]
Hello, I really appreciate for this awesome layout tool.

But I got a some issues when I try to use 'horizontal' splitter.
If I try to resize the horizontal bar, there are Type error 'Cannot read property 'getBoundingClientRect' of null'.
This error takes place in Splitter.js. line 149, 132.

Could you check this errors?

**Comment by martinnov92** [comment]
Hello @Widus , thank you for your kind words. Can you please provide some simple demo as I am not able to reproduce this issue. Thank you

**Comment by Jefski14** [comment]
I got the same Issue (but using vertical splitter), but i'm not sure what caused it. I upgraded redux to 4.0.0, had this error and found this issue, then downgraded again and it worked fine again, then i upgraded again to see if the error would come again but now it works fine, weird ...

**Comment by Jefski14** [comment]
I got this simple Demo reproducing the error: https://codesandbox.io/s/7l1o2lk01

**Comment by Jefski14** [comment]
I know how to reproduce the error now: 
1. Open my demo: [https://codesandbox.io/s/7l1o2lk01](url)
2. Change something in the code (add text for example)
3. See the Errors

**Comment by martinnov92** [comment]
I just released new version. Hope this issue is fixed for you

**Comment by don-p** [comment]
This error still exists:

```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Splitter._this.getSize (Splitter.js:205)
```

From what I can see, this may be a problem with multiple instances of the Splitter object in one application.  For example, in my application I have two main tabs which each contain a Splitter.  I see that the `Splitter.componentDidMount` adds a window `resize` event listener, that calls `_this.getSize`.  It seems to me that this could cause a problem, since only the currently-rendered object should be responding to `window.resize` events.

And, a non-rendered `Splitter` object will have a null reference to its `paneWrapper` property -
```
      ref: function ref(node) {
        return _this.paneWrapper = node;
      }
```

@martinnov92 Have you tested this component in a case like this, with two instances of `Splitter` in visible and hidden parent tabs?

Thanks,
Don
